validate response

diff --git a/.github/workflows/update_publish.yml b/.github/workflows/update_publish.yml
--- a/.github/workflows/update_publish.yml
+++ b/.github/workflows/update_publish.yml
@@ -35,7 +35,13 @@ jobs:
             echo "`nNew update exists"
 
             echo "`nPublishing new update to Chocolatey"
-            Push-Package
+            $response = Push-Package
+            
+            echo "TODO CHECKING FAILED RESPONSES"
+            $response
+            $LastExitCode
+            $?
+            echo "TODO DONE"
 
             echo "`nCommiting to Git"
             git config --global user.email "choco_package_updater@flowlauncher.com"
